import urllib.request
import xml.etree.ElementTree as etree

def main():

    #서울공공데이터사용
    url = "http://openapi.elevator.go.kr/openapi/service/ElevatorInformationService/getElevatorList?ServiceKey=3aeLNrMG9KdjsumqSulelgdmCWkU0278EVlfQjwDPLGCp6v6GHkn9ePF7mz03Sw8JtdAMEKhBIlcnNONUpNGVA%3D%3D" 

    data = urllib.request.urlopen(url).read()

    filename = "elevator.xml"
    f = open(filename, "wb") #다른 사람들의 예제처럼 "w"만 해서 했더니 에러가 발생
    f.write(data)
    f.close()

    #파싱하기
    tree = etree.parse(filename)
    root = tree.getroot()

    for a in root.findall('item'):
        print('소재지1')
        print(a.findtext('address1'))
        print('소재지2')
        print(a.findtext('address2'))
        print('운행유효기간(시작일)')
        print(a.findtext('applcBeDt'))
        print('운행유효기간(종료일)')
        print(a.findtext('applcEnDt'))
        print('지역번호')
        print(a.findtext('areaNo'))
        print('건물관리번호1')
        print(a.findtext('buldMgtNo1'))
        print('건물관리번호2')
        print(a.findtext('buldMgtNo2'))
        print('건물명')
        print(a.findtext('buldNm'))
        print('건물용도명')
        print(a.findtext('buldPrpos'))
        print('지상운행층수')
        print(a.findtext('divGroundFloorCnt'))
        print('지하운행층수')
        print(a.findtext('divUndgrndFloorCnt'))
        print('승강기번호')
        print(a.findtext('elevatorNo'))
        print('승강기호기')
        print(a.findtext('elvtrAsignNo'))
        print('승강기구분명')
        print(a.findtext('elvtrDivNm'))
        print('승강기형식명')
        print(a.findtext('elvtrFormNm'))
        print('승강기종류명')
        print(a.findtext('elvtrKindNm'))
        print('승강기관리번호1')
        print(a.findtext('elvtrMgtNo1'))
        print('승강기관리번호2')
        print(a.findtext('elvtrMgtNo2'))
        print('모델명')
        print(a.findtext('elvtrModel'))
        print('승강기재개일')
        print(a.findtext('elvtrResmptDe'))
        print('승강기상태')
        print(a.findtext('elvtrStts'))
        print('최종검사기관')
        print(a.findtext('inspctInstt'))
        print('설치일자')
        print(a.findtext('installationDe'))
        print('설치장소')
        print(a.findtext('installationPlace'))
        print('최종검사일')
        print(a.findtext('lastInspctDe'))
        print('최종검사종류')
        print(a.findtext('lastInspctKind'))
        print('최종검사결과')
        print(a.findtext('lastResultNm'))
        print('적재하중')
        print(a.findtext('liveLoad'))
        print('제조업체명')
        print(a.findtext('manufacturerName'))
        print('제조업체명전화번호')
        print(a.findtext('manufacturerTelno'))
        print('제조업체코드')
        print(a.findtext('mnfcturCpnyCd'))
        print('보수업체코드')
        print(a.findtext('mntCpnyCd'))
        print('보수업체명')
        print(a.findtext('mntCpnyNm'))
        print('보수업체연락처')
        print(a.findtext('mntCpnyTelno'))
        print('관리주체명')
        print(a.findtext('partcpntNm'))
        print('관리주체연락처')
        print(a.findtext('partcpntTelno'))
        print('최대정원')
        print(a.findtext('ratedCap'))
        print('정격속도')
        print(a.findtext('ratedSpeed'))
        print('승강기운행층수')
        print(a.findtext('shuttleFloorCnt'))
        print('선임여부/운행관리자명')
        print(a.findtext('shuttleMngrNm'))
        print('운행관리자연락처')
        print(a.findtext('shuttleMngrTelno'))
        print('휴폐지일자')
        print(a.findtext('pauseAblDe'))
        print('휴폐지사유')
        print(a.findtext('pauseAbleResn'))
        print('승강기운행구간')
        print(a.findtext('shuttleSection'))
        print('시/군/구_코드')
        print(a.findtext('sigunguCd'))
        print('표준키번호')
        print(a.findtext('standardKey'))
        print('하도급/공동수급')
        print(a.findtext('subcntrCpny'))
        print('우편번호1')
        print(a.findtext('zipCd1'))
        print('우편번호2')
        print(a.findtext('zipCd2'))
        print('한페이지결과수')
        print(a.findtext('numOfRows'))
        print('페이지번호')
        print(a.findtext('pageNo'))
        print('----------------------')

if __name__ == "__main__":
    main()